package utils

import (
	"bytes"
	"log"
	"os/exec"
)

// Define function that returns the diff changes generated by the git diff command
func GetDiffChanges() string {
	// Add all changes to the staging area
	cmd := exec.Command("git", "add", ".")
	_, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	// Define the command to run
	cmd = exec.Command("git", "diff", "--staged")

	// Run the command
	diff, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Found diff changes")
	// Get the info of the committer
	cmd = exec.Command("git", "var", "GIT_COMMITTER_IDENT")
	committer, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	// Remove the part after > in the committer info
	committer = bytes.Split(committer, []byte(">"))[0]
	log.Println("Committer: " + string(committer))
	// Append the committer info to the diff
	diff = append(diff, []byte("\n\nCommitter: "+string(committer)+">")...)
	// Return the output as a string
	return string(diff)
}
